### ISSUE TITLE
Rename Access Methods to be Consistent

### ISSUE THREAD

**Issue by terrellt** [projecthydra-labs/hydra-works#141] opened 2015-07-08 16:02 UTC
Use (#child/#parent)_collections and (#child/#parent)_objects to get objects/collections up and down the graph for both objects and collections.

**Comment by elrayle** [comment] 2015-07-13 18:43
Duplicate of https://github.com/projecthydra-labs/hydra-works/issues/149 which has more details.  Closing this one.

**Closed by elrayle** 2015-07-13 18:43 UTC
Labels: pcdm
